import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar/navbar'
import Footer from '@/components/Footer/footer'
import { SearchProvider } from '../context/search/SearchContext';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SearchProvider>  
          <Navbar/>
            {children}
          <Footer/>  
        </SearchProvider>  
      </body>
    </html>
  )
}
